#!/bin/bash

#
# Enter ssh to bypass apparmor
#


# Create ssh key to can ssh localhost
if [ ! -f /home/phablet/.ssh/ontheroad_key.pub ]; then
	clear
	echo "On The Road CLI"
	echo "---------------"
	echo
	echo "It's your first time running the On The Road CLI."
	echo "On The Road containers don't work with the restrictions of AppArmor."
	echo "To bypass them is enought to use ssh to connect back to the device."
	echo "It's needed to to this configuration process only once."
	echo "Now we are going to configure ssh."
	echo
	echo "Press 'q' to abort, anything else to continue"
	read i
	if [ "$i" == "q" ]; then
		exit
	fi
	clear
	echo "-------------------"
	echo "Creating ssh key..."
	echo
	echo "log:"
	echo
	if [ ! -d /home/phablet/.ssh ]; then
		mkdir /home/phablet/.ssh
	fi
	ssh-keygen -t rsa -N "" -f /home/phablet/.ssh/ontheroad_key
	cat /home/phablet/.ssh/ontheroad_key.pub >> /home/phablet/.ssh/authorized_keys
	clear
	echo "-----"
	echo "Done!"
	echo
	echo "Press something to continue..."
	read -n 1 -s
fi

# Start ssh server if stopped
sshstatus=$(/etc/init.d/ssh status)
if [ "$sshstatus" == "ssh stop/waiting" ]; then
	clear
	echo "Insert user password to start ssh server"
	echo
	sudo /etc/init.d/ssh start
fi

# Enter apparmorless shell
ssh -t localhost '/opt/click.ubuntu.com/ontheroad.emanuelesorce/current/scripts/ontheroad-cli'
